server:
  port: 58080

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
